[package]
name = "milky-mock-server"
version = "0.1.0"
edition = "2024"

[dependencies]
better-panic = "0.3.0"
cfg-if = "1.0.4"
color-eyre = "0.6.5"
ratatui = "0.29.0"
reqwest = "0.12.24"
tokio = { version = "1.48.0", features = ["full"] }
